# The URL the site will be built for
base_url = "https://dmkeijzer.github.io/project-portfolio/"

theme = "project-portfolio"

taxonomies = [
    {name = "projects", paginate_by = 5, feed = true},
    {name = "skills", paginate_by = 5, feed = true},
    {name = "CV", paginate_by = 5, feed = true},
]

[translations]
language_symbol = "ðŸ‡¬ðŸ‡§"
home = "Home"
projects = "Projects"
skills = "Skills"
read_more = "Read More"
skills_technologies = "Skills & Technologies"
main_skills = "Main Skills"
other_skills = "Additional Skills"



[extra.navbar]
title = "Portfolio Damien Keijzer"
items = [
  { lang = "en", links = [{ url = "cv", name = "CV" }] }
]


[extra.index]
title = " Damien Keijzer"
slogan = "The only way to go fast is to go well. - Robert C. Martin" 
image = "portrait_damien.jpg"
image_alt = "Photo of Damien Keijzer"

[extra.social]
github = "https://github.com/dmkeijzer"
linkedin = "https://www.linkedin.com/in/damien-keijzer-b3a172221/"
email = "damien.keijzer@gmail.com"
